### ISSUE TITLE
Проблема с занимаемым местом ПО

### ISSUE THREAD

**Issue by Krivtsov1** [ulta-plus/vpnn-client#24]
Когда какое-то время пользуешься приложением, оно куда-то крадет 4-6 ГБ.
Если установить и сразу удалить - такое не замечали.

**Comment by Vipon** [comment]
Судя по всему проблема в логах:

C:\programdata\vpnnaruzhu

**Comment by Vipon** [comment]
Проблема больше не воспроизводится. Видимо, была решена.
